# Generated by Django 3.1.3 on 2020-11-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/Public')),
                ('default', models.BooleanField(default=False)),
                ('galery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imagegalery')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='image_gallery',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.imagegalery'),
            preserve_default=False,
        ),
    ]
