# Generated by Django 3.1.3 on 2020-11-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201111_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='expires_in',
            new_name='expires_on',
        ),
    ]
