# Generated by Django 3.1.3 on 2020-11-14 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201114_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image_gallery',
        ),
        migrations.AddField(
            model_name='imagegalery',
            name='offer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expires_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='view_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
