# Generated by Django 3.1.3 on 2020-11-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201114_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='galery_id',
            new_name='galery',
        ),
    ]
