# Generated by Django 3.1.3 on 2020-11-21 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20201114_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='image',
            field=models.ImageField(upload_to='c:\\Users\\pe6ka\\VisualStudioCodeProjects\\Python_web\\bidster\\bidster\\media\\categories'),
        ),
    ]
