# Generated by Django 3.1.3 on 2020-11-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_bid_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='offer',
            new_name='for_offer',
        ),
        migrations.AddField(
            model_name='bid',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='highest_bid',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='view_counts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\pe6ka\\VisualStudioCodeProjects\\Python_web\\bidster\\bidster\\media\\categories'),
        ),
    ]
