# Generated by Django 3.1.3 on 2020-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201129_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='offer',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='image',
            field=models.ImageField(upload_to='c:\\Users\\pe6ka\\VisualStudioCodeProjects\\Python_web\\bidster\\bidster\\media\\categories'),
        ),
    ]
