# Generated by Django 3.1.3 on 2020-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201129_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='offer',
            name='contact_person',
            field=models.CharField(default='Peter', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='contact_phone',
            field=models.CharField(default='+123', max_length=50),
            preserve_default=False,
        ),
    ]
