# Generated by Django 3.1.3 on 2020-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201205_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercategory',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\pe6ka\\VisualStudioCodeProjects\\Python_web\\bidster\\bidster\\media\\categories'),
        ),
    ]
