# Generated by Django 3.1.3 on 2020-12-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201206_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegalery',
            options={'verbose_name_plural': 'Image galeries'},
        ),
        migrations.AlterModelOptions(
            name='offercategory',
            options={'verbose_name_plural': 'Offer categories'},
        ),
        migrations.RemoveField(
            model_name='imagegalery',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='image_galery',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.imagegalery'),
            preserve_default=False,
        ),
    ]
